# Generated by Django 3.0.6 on 2020-07-06 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelbabysitter',
            old_name='num_of_kids',
            new_name='max_kids',
        ),
    ]
